Degrad_card:
  energy: 11800
  input_file: input.card
  n_tracks: 400
  seed: 42
Gas_props:
  W: 34.2
  sigmaL: 167
  sigmaL_induc: 158
  sigmaL_trans: 218
  sigmaT: 264
  sigmaT_induc: 359
  sigmaT_trans: 590
  vd: 130
Migdal_sim:
  ER_input_filepath: data/20000ERs_2-11.8keV.feather
  NR_input_filepath: RCTRIM/output/F_maxE466.957_18359primaryTracks.feather
  output_directory: migdal_primary_tracks/
  randomize: false
Sim_settings:
  apply_amplification: true
  apply_drift: true
  digitize: true
  overwrite_output: true
  parallel: true
  parallel_chunks: 40
  randomize_primary_track_order: true
  rotate_tracks: true
  write_gain: false
TPC_sim:
  GEM2_offsetx: 0
  GEM2_offsety: 0
  GEM_height: 5
  GEM_thickness: 0.057
  GEM_width: 5
  gain: 90000
  hole_diameter: 170
  hole_pitch: 280
  induction_gap: 0.2
  transfer_gap: 0.2
