input_file: 'input.card' #Name of input card file. run_and_process_degrad.py adjusts the parameters below in the card file

n_tracks: 10000 #Number of ERs to simulate

seed: 42 #Use what you want here

energy: 5900 #In eV

rotate_tracks: True #Set to True if you want to rotate the primary tracks so they are isotropic. Otherwise primary tracks are (1,0,0)